### ISSUE TITLE
Project maintenance: "failed build" action issue

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/otp_builds#3]
Think about using https://github.com/jayqi/failed-build-issue-action.

It'd help us be notified in the case of a failed build and links to the step that did. Maybe it's also possible to get notified in the `/notifications` natively (?), but I've never had real success with that.

Example implementation is as simple as having the following as a final build step

```
      - name: Notify on failed build
        uses: jayqi/failed-build-issue-action@v1.2.0
        if: failure() && github.ref == 'refs/heads/main'
                                        ^ adjust to our use case
        id: failed-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
